version: '3.8'

services:
  db:
    image: postgres:15  # You can specify any version of PostgreSQL
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Maps container's port 5432 to host's port 5432
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data

volumes:
  db_data: